apiVersion: v1
kind: Service
metadata:
  name: audit-trail
  labels:
    app.kubernetes.io/name: audit-trail
spec:
  selector:
    app.kubernetes.io/name: audit-trail
  ports:
    - name: http
      port: 3006
      targetPort: 3006
  type: ClusterIP
