apiVersion: v1
kind: Service
metadata:
  name: collaboration
  labels:
    app.kubernetes.io/name: collaboration
spec:
  selector:
    app.kubernetes.io/name: collaboration
  ports:
    - name: http
      port: 3004
      targetPort: 3004
  type: ClusterIP
