apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification
spec:
  selector:
    app.kubernetes.io/name: notification
  ports:
    - name: http
      port: 3007
      targetPort: 3007
  type: ClusterIP
